NBAJam/Controllers/PlayerController.cs
using Microsoft.AspNetCore.Mvc;
using NBAJam.Models;
using NBAJam.Data;

namespace NBAJam.Controllers
{
    public class PlayerController : Controller
    {
        private Repository<Player> _players;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public PlayerController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _players = new Repository<Player>(context);

            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _players.GetAllAsync());
        }

        [HttpGet]
        public async Task<IActionResult> AddEdit(int id)
        {
            ViewBag.AllPlayers = await _players.GetAllAsync();
            if (id == 0)
            {
                //add
                ViewBag.Operation = "Add";
                return View(new Player());
            }
            else
            {
                Player player = await _players.GetByIdAsync(id, new QueryOptions<Player>
                {
                    Includes = "",
                });
                ViewBag.Operation = "Edit";
                return View(player);
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlayerId, Name")] Player player, bool playerPage)
        {
            if (ModelState.IsValid)
            {
                await _players.AddAsync(player);
                if (playerPage)
                    return RedirectToAction("Index");
                else
                    return RedirectToAction("PlayerSetup", "Tournament");
            }
            return View(player);
        }

        public async Task<IActionResult> Details(int id)
        {
            return View(await _players.GetByIdAsync(id, new QueryOptions<Player>() { Includes = "PlayerTournaments.Tournament" }));           
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            return View(await _players.GetByIdAsync(id, new QueryOptions<Player>() { Includes = "PlayerTournaments.Tournament" }));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Player player)
        {
            if (ModelState.IsValid)
            {
                await _players.UpdateAsync(player);
                return RedirectToAction("Index");
            }
            return View(player);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Player player)
        {
            await _players.DeleteAsync(player.PlayerId);
            return RedirectToAction("Index");
        }
        
    }
}

NBAJam/Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;
using NBAJam.Models;
using NBAJam.Data;

namespace NBAJam.Controllers
{
    public class TeamController : Controller
    {
        private Repository<Team> _teams;
        private Repository<Game> _games;
        private Repository<Tournament> _tournaments;
        private Repository<Round> _rounds;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public TeamController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _teams = new Repository<Team>(context);
            _games = new Repository<Game>(context);
            _tournaments = new Repository<Tournament>(context);
            _rounds = new Repository<Round>(context);

            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            var teams = await _teams.GetAllAsync(new QueryOptions<Team>
            {
                Includes = "PlayerTeams, PlayerTeams.Player, TeamTournaments.Tournament"
            });

            if (teams != null)
            {
                foreach (var team in teams)
                {
                    team.TournamentsWon = 0;
                    foreach (var teamTournament in team.TeamTournaments)
                    {
                        if (teamTournament.Tournament.WinningTeamId == team.TeamId)
                            team.TournamentsWon++;
                    }
                }
            }

            return View(teams);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            Team buyTeam = await _teams.GetByIdAsync(1, new QueryOptions<Team> { });


            IEnumerable<Game> games = await _games.GetAllAsync(new QueryOptions<Game> { Includes = "Team1, Team2" });
            foreach (Game game in games)
            {
                if (game.Team1?.TeamId == id)
                {
                    game.Team1 = buyTeam;
                    await _games.UpdateAsync(game);
                }
                if (game.Team2?.TeamId == id)
                {
                    game.Team2 = buyTeam;
                    await _games.UpdateAsync(game);
                }
            }

            IEnumerable<Tournament> tournaments = await _tournaments.GetAllAsync(new QueryOptions<Tournament> { Includes = "TeamTournaments" });
            foreach (Tournament tournament in tournaments)
            {
                foreach (TeamTournament teamTournament in tournament.TeamTournaments)
                {
                    if (teamTournament.TeamId == id)
                    {
                        tournament.TeamTournaments.Remove(teamTournament);
                        await _tournaments.UpdateAsync(tournament);
                        break;
                    }    
                }
            }

            Team team = await _teams.GetByIdAsync(id, new QueryOptions<Team> { Includes = "TeamTournaments" });
            team.TeamTournaments.Clear();
            await _teams.UpdateAsync(team);

            await _teams.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

NBAJam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NBAJam</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NBAJam.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NBAJam</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tournament" asp-action="Index">Tournaments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Index">Players</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Team" asp-action="Index">Teams</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - NBAJam - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $(document).ready(function () {
            $('.modal').on('shown.bs.modal', function () {
                $(this).css('display', 'block');
            });
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>