NBAJam/Models/Player.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace NBAJam.Models
{
    public class Player
    {       
        public int PlayerId { get; set; }
        public string Name { get; set; }

        [ValidateNever] public List<PlayerTeam> PlayerTeams { get; set; }

        public int TournamentsWon { get; set; }

        [ValidateNever] public ICollection<PlayerTournament> PlayerTournaments { get; set; }

        public Player()
        {
            PlayerTeams = new List<PlayerTeam>();   
        }
    }
}

NBAJam/Models/PlayerViewModel.cs
namespace NBAJam.Models
{
    public class PlayerViewModel
    {
        public Player Player { get; set; }
        public bool ReturnToPlayerPage { get; set; }
    }
}

NBAJam/Controllers/PlayerController.cs
using Microsoft.AspNetCore.Mvc;
using NBAJam.Models;
using NBAJam.Data;

namespace NBAJam.Controllers
{
    public class PlayerController : Controller
    {
        private Repository<Player> _players;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public PlayerController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _players = new Repository<Player>(context);

            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _players.GetAllAsync());
        }

        [HttpGet]
        public async Task<IActionResult> AddEdit(int id)
        {
            ViewBag.AllPlayers = await _players.GetAllAsync();
            if (id == 0)
            {
                //add
                ViewBag.Operation = "Add";
                return View(new Player());
            }
            else
            {
                Player player = await _players.GetByIdAsync(id, new QueryOptions<Player>
                {
                    Includes = "",
                });
                ViewBag.Operation = "Edit";
                return View(player);
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlayerId, Name")] Player player, bool playerPage)
        {
            if (ModelState.IsValid)
            {
                await _players.AddAsync(player);
                if (playerPage)
                    return RedirectToAction("Index");
                else
                    return RedirectToAction("PlayerSetup", "Tournament");
            }
            return View(player);
        }

        public async Task<IActionResult> Details(int id)
        {
            return View(await _players.GetByIdAsync(id, new QueryOptions<Player>() { Includes = "PlayerTournaments.Tournament" }));           
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            return View(await _players.GetByIdAsync(id, new QueryOptions<Player>() { Includes = "PlayerTournaments.Tournament" }));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Player player)
        {
            if (ModelState.IsValid)
            {
                await _players.UpdateAsync(player);
                return RedirectToAction("Index");
            }
            return View(player);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Player player)
        {
            await _players.DeleteAsync(player.PlayerId);
            return RedirectToAction("Index");
        }
        
    }
}

NBAJam/ViewComponents/CreatePlayerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NBAJam.Data;
using NBAJam.Models;

namespace NBAJam.ViewComponents
{
    public class CreatePlayerViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(bool returnToPlayerPage)
        {
            Player player = new Player();
            PlayerViewModel playerViewModel = new PlayerViewModel();
            playerViewModel.ReturnToPlayerPage = returnToPlayerPage;
            return View(playerViewModel);

          
        }

    }
}

NBAJam/Views/Player/Create.cshtml
@model Player

@{
    ViewBag.Title = "Create Player";
}


<div id="partialZone">
    @await Component.InvokeAsync("CreatePlayer", new { returnToPlayerPage = true })
</div>
<a asp-action="Index" class="btn btn-secondary">Back to List</a>

NBAJam/Views/Player/Details.cshtml
@model Player

@{
    ViewBag.Title = "Player Details";
}

<h1>@Model.Name Details</h1>

<div>
    <a asp-action="Index">Back to List</a>
</div>

NBAJam/Views/Player/Edit.cshtml
@model Player

@{
    ViewBag.Title = $"Edit {Model.Name} Player";
}

@functions {
    string GetDeleteModalId(int playerId)
    {
        return "#deleteModal" + playerId;
    }

    string GetModalId(int playerId)
    {
        return "deleteModal" + playerId;
    }
}

<h3>Edit Player</h3>

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="PlayerId" />
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />       
        <a asp-action="Index" class="btn btn-default">Back to List</a>
    </div>
</form>

<form asp-action="Delete" method="post">
    <input type="hidden" asp-for="PlayerId" />
    

    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="@GetDeleteModalId(Model.PlayerId)">
        <i class="bi bi-trash">Delete</i>
    </button>

    <div class="modal fade" id="@GetModalId(Model.PlayerId)" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Delete player?</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Delete"></button>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger">Confirm</button>
                </div>
            </div>
        </div>
    </div>
</form>

NBAJam/Views/Player/Index.cshtml
@model IEnumerable<Player>

@{
    ViewBag.Title = "Players";
}

<h2>Players </h2>
<a asp-action="Create" asp-controller="Player" class="btn btn-primary">Create New Player</a>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(Player player in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => player.Name)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@player.PlayerId">Details</a>
                    <a asp-action="Edit" asp-route-id="@player.PlayerId">Edit</a>                    
                </td>
            </tr>
        }
    </tbody>
</table>