NBAJam/Models/BracketSetupViewModel.cs
namespace NBAJam.Models
{
    public class BracketSetupViewModel
    {
        public int TournamentId { get; set; }
        public string TournamentName { get; set; }
        public List<Team> Teams { get; set; }
        public List<int> TeamIds { get; set; }
        public List<Player> Players { get; set; }
        public List<int> PlayerIds { get; set; }

        public BracketSetupViewModel()
        {
            Teams = new List<Team>();
            TeamIds = new List<int>();

            Players = new List<Player>();
            PlayerIds = new List<int>();
        }

    }
}

NBAJam/Models/Tournament.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace NBAJam.Models
{
    public class Tournament
    {
        public int TournamentId { get; set; }
        public string Name { get; set; }
        public List<Round> Rounds { get; set; }
        [ValidateNever] public ICollection<TeamTournament> TeamTournaments { get; set; }
        [ValidateNever] public ICollection<PlayerTournament> PlayerTournaments { get; set; }
        public int WinningTeamId { get; set; }

        [NotMapped] public int TotalGames
        {
            get
            {                
                int totalGames = 0;
                foreach (Round round in Rounds)
                {
                    foreach (int gameId in round.GameIds)
                    {
                        totalGames++;
                    }
                }
                return totalGames;
            }
        }

        public int GamesPlayed { get; set; }
        public Tournament()
        {
            PlayerTournaments = new List<PlayerTournament>();
            TeamTournaments = new List<TeamTournament>();
            Rounds = new List<Round>();
            GamesPlayed = 0;
        }
    }
}

NBAJam/Controllers/TournamentController.cs
using Microsoft.AspNetCore.Mvc;
using NBAJam.Models;
using NBAJam.Data;

using Microsoft.EntityFrameworkCore;
using System.Runtime.InteropServices.Marshalling;

namespace NBAJam.Controllers
{
    public class TournamentController : Controller
    {
        private Repository<Tournament> _tournaments;
        private Repository<Player> _players;
        private Repository<Team> _teams;
        private Repository<Game> _games;
        private Repository<Round> _rounds;

        private readonly IWebHostEnvironment _webHostEnvironment;

        private Random _rng;

        public TournamentController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _tournaments = new Repository<Tournament>(context);
            _players = new Repository<Player>(context);
            _teams = new Repository<Team>(context);
            _games = new Repository<Game>(context);
            _rounds = new Repository<Round>(context);

            _rng = new Random();

            _webHostEnvironment = webHostEnvironment;

        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Tournament> tournaments = await _tournaments.GetAllAsync(new QueryOptions<Tournament> { Includes = "Rounds" });            

            ViewBag.TeamNames = new Dictionary<int, string>();

            foreach (Tournament tournament in tournaments)
            {
                Team winningTeam = await _teams.GetByIdAsync(tournament.WinningTeamId, new QueryOptions<Team>{ Includes = "PlayerTeams, PlayerTeams.Player" });
                if (winningTeam != null)
                    ViewBag.TeamNames.TryAdd(tournament.TournamentId, winningTeam.Name);
            }
            return View(tournaments);
        }

        [HttpGet]
        public async Task<IActionResult> TournamentView(int id)
        {
            Tournament tournament = await _tournaments.GetByIdAsync(id, new QueryOptions<Tournament>
            {
                Includes = "PlayerTournaments.Player, TeamTournaments.Team, TeamTournaments.Team.PlayerTeams, TeamTournaments.Team.PlayerTeams.Player, Rounds",
            });           

            ViewBag.Rounds = (int)Math.Ceiling(Math.Log2(tournament.PlayerTournaments.Count / 2.0));

            bool updatedTournament = false;

            for (int i = 1; i < ViewBag.Rounds; i++)
            {
                if (tournament.Rounds.ElementAtOrDefault(i) == null)
                {
                    tournament.Rounds.Add(new Round() { RoundNumber = i });
                    updatedTournament = true;
                }
            }

            Team winningTeam = await _teams.GetByIdAsync(tournament.WinningTeamId, new QueryOptions<Team>
            {
                Includes = "PlayerTeams, PlayerTeams.Player",
            });
            ViewBag.WinningTeamName = winningTeam?.Name;


            ViewBag.Games = new int[ViewBag.Rounds];

            int gameCount = 1;
            for (int i = ViewBag.Rounds - 1; i >= 0; i--)
            {
                ViewBag.Games[i] = gameCount;
                for (int j = 0; j < gameCount; j++)
                {  
                    if (j >= tournament.Rounds[i].GameIds.Count || (j < tournament.Rounds[i].GameIds.Count && tournament.Rounds[i].GameIds[j] == 0))
                    {
                        Game newGame = new Game() { TournamentId = id, Tournament = tournament };
                        await _games.AddAsync(newGame);
                        if (newGame != null && newGame.GameId != 0)
                        {
                            tournament.Rounds[i].GameIds.Add(newGame.GameId);
                            updatedTournament = true;
                        }
                    }
                }

                gameCount *= 2;
            }

            //check byes and games Played
            int roundIndex = 0;
            int gamesPlayed = 0;
            foreach (Round round in tournament.Rounds)
            {
                int gameIndex = 0;
                foreach (int gameId in round.GameIds)
                {
                    Game game = await _games.GetByIdAsync(gameId, new QueryOptions<Game> { Includes = "Team1, Team2" });

                    int newGameIndex = gameIndex / 2;
                    int newGameId = tournament.Rounds.ElementAtOrDefault(roundIndex+1)?.GameIds.ElementAtOrDefault(newGameIndex) ?? 0;

                    Game newGame = await _games.GetByIdAsync(newGameId, new QueryOptions<Game> { Includes = "Team1, Team2" });
                    if (game != null && game.Team1 != null && game.Team1.ByeTeam)
                    {
                        if (newGame != null)
                        {
                            if (gameIndex % 2 == 0 && newGame.Team1 == null)
                            {
                                newGame.Team1 = game.Team2;
                                await _games.UpdateAsync(newGame);
                                updatedTournament = true;
                            }
                            else if (gameIndex % 2 != 0 && newGame.Team2 == null)
                            {
                                newGame.Team2 = game.Team2;
                                await _games.UpdateAsync(newGame);
                                updatedTournament = true;
                            }                           
                        }
                        game.Team2Won = true;
                        game.Team1Won = false;
                    }
                    else if (game != null && game.Team2 != null && game.Team2.ByeTeam)
                    {
                        if (newGame != null)
                        {
                            if (gameIndex % 2 == 0 && newGame.Team1 == null)
                            {
                                newGame.Team1 = game.Team1;
                                await _games.UpdateAsync(newGame);
                                updatedTournament = true;
                            }
                            else if (gameIndex % 2 != 0 && newGame.Team2 == null)
                            {
                                newGame.Team2 = game.Team1;
                                await _games.UpdateAsync(newGame);
                                updatedTournament = true;
                            }                           
                        }
                        game.Team1Won = true;
                        game.Team2Won = false;
                    }

                    if (game.GamePlayed)
                        gamesPlayed++;

                    gameIndex++;
                }
                roundIndex++;
            }

            if (gamesPlayed != tournament.GamesPlayed && gamesPlayed <= tournament.TotalGames && gamesPlayed >= 0)
            {
                tournament.GamesPlayed = gamesPlayed;
                updatedTournament = true;
            }


            if (updatedTournament)
                await _tournaments.UpdateAsync(tournament);


            // Fetch games for each round
            Dictionary<int, List<Game>> roundGames = new Dictionary<int, List<Game>>();
            foreach (Round round in tournament.Rounds)
            {
                List<Game> games = new List<Game>();
                foreach (int gameId in round.GameIds)
                {
                    Game game = await _games.GetByIdAsync(gameId, new QueryOptions<Game> { Includes = "Team1, Team2" });
                    if (game != null)
                    {
                        games.Add(game);
                    }
                }
                roundGames[round.RoundNumber] = games;
            }
            ViewBag.RoundGames = roundGames;

            return View(tournament);
        }

        [HttpGet]
        public async Task<IActionResult> BracketSetup(TeamTournamentViewModel teamTournamentViewModel)
        {
            Tournament tournament = await _tournaments.GetByIdAsync(teamTournamentViewModel.TournamentId, new QueryOptions<Tournament>
            {
                Includes = "PlayerTournaments.Player, TeamTournaments.Team, Rounds, TeamTournaments.Team.PlayerTeams",
            });            

            

            
            ViewBag.Rounds = (int)Math.Ceiling(Math.Log2(teamTournamentViewModel.PlayerIds.Count / 2.0));
            ViewBag.Games = new int[ViewBag.Rounds];

            int gameCount = 1;
            for (int i = ViewBag.Rounds - 1; i >= 0; i--)
            {
                ViewBag.Games[i] = gameCount;
                gameCount *= 2;
            }
            List<Team> teams = new List<Team>();
            if (tournament != null)
            {
                Team byeTeam = await _teams.GetByIdAsync(1, new QueryOptions<Team> { Includes = "PlayerTeams, PlayerTeams.Player" });
                foreach (int gameId in tournament.Rounds[0].GameIds)
                {
                    Game game = await _games.GetByIdAsync(gameId, new QueryOptions<Game> { Includes = "Team1, Team2" });
                    if (game != null && game.Team1 != null)
                        teams.Add(game.Team1);
                    if (game != null && game.Team2 != null)
                        teams.Add(game.Team2);
                }
             
                teams.Add(byeTeam);
            }
            else
            {
                int teamCount = 0;
                foreach (int teamId in teamTournamentViewModel.TeamIds)
                {
                    if (teamId != 1)
                        teamCount++;

                    Team team = await _teams.GetByIdAsync(teamId, new QueryOptions<Team> { Includes = "PlayerTeams, PlayerTeams.Player" });
                    teams.Add(team);
                }


                if (teamTournamentViewModel.RandomSetup)
                {
                    teams = teams.OrderBy(_ => _rng.Next()).ToList();
                    List<int> bracketTeamIds = new List<int>(new int[ViewBag.Games[0] * 2]);

NBAJam/ViewComponents/CreatePlayerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NBAJam.Data;
using NBAJam.Models;

namespace NBAJam.ViewComponents
{
    public class CreatePlayerViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(bool returnToPlayerPage)
        {
            Player player = new Player();
            PlayerViewModel playerViewModel = new PlayerViewModel();
            playerViewModel.ReturnToPlayerPage = returnToPlayerPage;
            return View(playerViewModel);

          
        }

    }
}

NBAJam/Views/Tournament/AddEdit.cshtml
@model PlayerTournamentViewModel

@{
    ViewBag.Title = $"{ViewBag.Operation} Tournament";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Drag and Drop Colored Squares</title>
    <style>
        #pool {
            display: flex;
            flex-wrap: wrap;
            gap: 10px;
            padding: 20px;
            border: 1px solid #ccc;
        }

        .square {
            height: 40px;
            width: auto;
            max-width: 200px;
            cursor: move;
            border: 2px solid black;
            position: relative;
            display: flex; /* Key for dynamic width */
            align-items: center; /* Key for vertical centering */
            padding: 0 10px; /* Add some padding for visual comfort */
            box-shadow: 0 0 10px rgba(0,0,0,.05), 2px 2px 5px rgba(0,0,0,.75);
            border-radius: 14px;
            white-space: nowrap; /* Prevent text from wrapping */
            min-width: 100px;
        }

        .square .name {
            color: black;
            font-weight: bold;
            /* Remove unnecessary positioning styles */
            margin: 0 auto; /* Center the text horizontally */
            /* No need for position: absolute, top, vertical-align */
            overflow: hidden; /* Hide overflowing text */
            text-overflow: ellipsis; /* Add ellipsis (...) for overflow */
            white-space: nowrap; /* Prevent text from wrapping */
            margin-right: 25px; /* Add space for the 'x' */
            margin-left: 0;
        }

        .square .x {
            color: red;
            font-weight: bold;
            right: 10px;
            /* Remove unnecessary positioning styles */
            margin: 0 auto; /* Center the text horizontally */
            position: absolute;
            /* No need for position: absolute, top, vertical-align */
            display: none; /* Hidden by default */
            cursor: pointer;
        }

            
        #drop-zone .square:hover span {
            display: block;
        }        

        #drop-zone {
            /*width: 300px;*/
            height: 200px;
            border: 1px dashed #ccc;
            margin: 20px auto; /* Center the drop zone */
            display: flex;
            flex-wrap: wrap; /* Allow multiple squares to be dropped */
            gap: 10px;
            padding: 10px;
        }

        #log {
            margin-top: 20px;
            border: 1px solid #ccc;
            padding: 10px;
            height: 100px;
            overflow-y: scroll;
        }
    </style>
</head>
<body>

    <h1>Select Players</h1>

    <div id="pool">Pool 

        @foreach (Player player in ViewBag.AllPlayers)
        {
            <div id="@player.PlayerId" class="square" draggable="true" ondragenter="dragEnter(event)" ondragstart="event.dataTransfer.setData('text', '@player.PlayerId')" ondragleave="dragLeave(event)" ondragover="dragOver(event)">
                <span class="name">@player.Name</span>
                <span class="x">x</span>
            </div>
        }
    </div>

    <div id="drop-zone">Tournament Players
        
    </div>


    <div id="partialZone">
        @await Component.InvokeAsync("CreatePlayer", new { returnToPlayerPage = false })
    </div>

    <form asp-action="AddEdit" method="post" enctype="multipart/form-data">   
        <input type="hidden" asp-for="TournamentId" />

        <div class="form-group">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" name="Name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="form-check">
            <input type="checkbox" asp-for="RandomTeams" checked />
            <label class="form-check-lable" for="RandomTeams">Random Teams</label>
        </div>

        @foreach (Player player in ViewBag.AllPlayers)
        {
            <div class="form-check">
                @{
                    bool isChecked = Model.Players != null && Model.Players.Any(i => i.PlayerId == player.PlayerId);
                }
                <input type="checkbox" class="form-check-input" id="@player.PlayerId" name="playerIDs" value="@player.PlayerId"
                @(isChecked ? "checked" : "") />
                <label class="form-check-label" for="@player.PlayerId">@player.Name</label>
            </div>
        }
        <button tpye="submit" class="btn btn-primary">Create</button>
    </form>

    <script>
        const pool = document.getElementById('pool');
        const dropZone = document.getElementById('drop-zone');      
   

        function dragStart(event) 
        {
            event.dataTransfer.setData('text', event.squareId);
        }

        function dragEnter(event) 
        {
            event.preventDefault();
            dropZone.style.border = "2px dashed green";
        }

        function dragOver(event) 
        {
            event.preventDefault();
        }

        function dragLeave(event) 
        {
            dropZone.style.border = "1px dashed #ccc";
        }

        function dragDrop(event) 
        {
            event.preventDefault();
            dropZone.style.border = "1px dashed #ccc";
            const draggedElementId = event.dataTransfer.getData('text');
            const draggedElement = document.getElementById(draggedElementId);
            if (draggedElement) {
                dropZone.appendChild(draggedElement);
            }
        }

        dropZone.addEventListener('dragenter', (event) => {
            event.preventDefault();
            dropZone.style.border = "2px dashed green";            
        });

        dropZone.addEventListener('dragover', (event) => {
            event.preventDefault();            
        });

        dropZone.addEventListener('dragleave', (event) => {
            dropZone.style.border = "1px dashed #ccc";  
        });

        dropZone.addEventListener('drop', (event) => {
            event.preventDefault();
            dropZone.style.border = "1px dashed #ccc";
            const draggedElementId = event.dataTransfer.getData('text');
            const draggedElement = document.getElementById(draggedElementId);
            if (draggedElement) {
                dropZone.appendChild(draggedElement);
            }
        });

        // Event listener for the 'x' click
        dropZone.addEventListener('click', (event) => {
            if (event.target.className === 'x') { // Check if the 'x' was clicked
                const square = event.target.parentNode;
                const squareId = square.id;

                console.log(squareId);

                pool.appendChild(square); // Move back to the pool

                const antiForgeryToken = document.querySelector('input[name="__RequestVerificationToken"]').value; // Get the token from the form
                
                $.ajax({ // Use $.ajax for more control
                    type: "POST",
                    url: '@Url.Action("RemovePlayer", "Tournament")',
                    data: { playerId: squareId },
                    headers: {
                        "RequestVerificationToken": antiForgeryToken // Add the token to the headers
                    },
                    success: function (response) {
                        // Handle success (e.g., remove the element from the UI)
                        console.log("Player removed successfully");
                    },
                    error: function (error) {
                        // Handle errors
                        console.error("Error removing player:", error);
                    }
                });
            }
        });


      
    </script>

</body>
</html>

NBAJam/Views/Tournament/Index.cshtml
@model IEnumerable<Tournament>

@{
    ViewBag.Title = "Tournaments";
}

@functions {
    string GetDeleteModalId(int tournamentId)
    {
        return "#deleteModal" + tournamentId;
    }

    string GetModalId(int tournamentId)
    {
        return "deleteModal" + tournamentId;
    }
}

<head>
    <style>
        .outline {
            border: 2px solid black;
            box-shadow: 0 0 10px rgba(0,0,0,.05), 2px 2px 5px rgba(0,0,0,.75);
            border-radius: 14px;
        }
    </style>
</head>

<h2>Tournaments </h2>
<a asp-action="PlayerSetup" asp-controller="Tournament" class="btn btn-primary">Create New Tournament</a>

<div class="row">
    @foreach (Tournament tournament in Model)
    {
        <div class="col-md-4">
            <form asp-action="Delete" asp-controller="Tournament" method="post">
                <input type="hidden" asp-for="@tournament.TournamentId" name="id" />
                <div class="card-body outline">
                    <h3 class="card-title">@tournament.Name</h3>
                    <h5>Games Played: @tournament.GamesPlayed / @tournament.TotalGames</h5>
                    @if (tournament.WinningTeamId != 0 && ViewBag.TeamNames.ContainsKey(tournament.TournamentId))
                    {
                        <h4>Winner: @ViewBag.TeamNames[tournament.TournamentId]</h4>
                    }
                    <a asp-action="PlayerSetup" asp-controller="Tournament" asp-route-id="@tournament.TournamentId" class="btn btn-info"><i class="bg-info bi-pencil-fill">Edit</i></a>
                    <a asp-action="TournamentView" asp-controller="Tournament" asp-route-id="@tournament.TournamentId" class="btn btn-info"><i class="bg-info bi-pencil-fill">View</i></a>

                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="@GetDeleteModalId(tournament.TournamentId)">
                        <i class="bi bi-trash">Delete</i>
                    </button>

                </div>

                <div class="modal fade" id="@GetModalId(tournament.TournamentId)" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="exampleModalLabel">Delete tournament?</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Delete"></button>
                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-danger">Confirm</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        
    }
</div>

NBAJam/Views/Tournament/PlayerSetup.cshtml
@model PlayerTournamentViewModel

@{
    ViewBag.Title = $"{ViewBag.Operation} Tournament";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Drag and Drop Colored Squares</title>
    <style>
        #pool {
            display: flex;
            flex-wrap: wrap;
            gap: 10px;
            padding: 20px;
            border: 1px solid #ccc;
        }

        .square {
            height: 40px;
            width: auto;
            max-width: 200px;
            cursor: move;
            border: 2px solid black;
            position: relative;
            display: flex; /* Key for dynamic width */
            align-items: center; /* Key for vertical centering */
            padding: 0 10px; /* Add some padding for visual comfort */
            box-shadow: 0 0 10px rgba(0,0,0,.05), 2px 2px 5px rgba(0,0,0,.75);
            border-radius: 14px;
            white-space: nowrap; /* Prevent text from wrapping */
            min-width: 100px;
        }

        .square .name {
            color: black;
            font-weight: bold;
            /* Remove unnecessary positioning styles */
            margin: 0 auto; /* Center the text horizontally */
            /* No need for position: absolute, top, vertical-align */
            overflow: hidden; /* Hide overflowing text */
            text-overflow: ellipsis; /* Add ellipsis (...) for overflow */
            white-space: nowrap; /* Prevent text from wrapping */
            margin-right: 25px; /* Add space for the 'x' */
            margin-left: 0;
        }

        .square .x {
            color: red;
            font-weight: bold;
            right: 10px;
            /* Remove unnecessary positioning styles */
            margin: 0 auto; /* Center the text horizontally */
            position: absolute;
            /* No need for position: absolute, top, vertical-align */
            display: none; /* Hidden by default */
            cursor: pointer;
        }

            
        #drop-zone .square:hover span {
            display: block;
        }        

        #drop-zone {
            /*width: 300px;*/
            height: 200px;
            border: 1px dashed #ccc;
            margin: 20px auto; /* Center the drop zone */
            display: flex;
            flex-wrap: wrap; /* Allow multiple squares to be dropped */
            gap: 10px;
            padding: 10px;
        }

        #log {
            margin-top: 20px;
            border: 1px solid #ccc;
            padding: 10px;
            height: 100px;
            overflow-y: scroll;
        }
    </style>
</head>
<body>

    <h1>Select Players</h1>

    <div id="pool">Pool 

        @foreach (Player player in ViewBag.AllPlayers)
        {
            <div id="@player.PlayerId" class="square" draggable="true" ondragenter="dragEnter(event)" ondragstart="event.dataTransfer.setData('text', '@player.PlayerId')" ondragleave="dragLeave(event)" ondragover="dragOver(event)">
                <span class="name">@player.Name</span>
                <span class="x">x</span>
            </div>
        }
    </div>

    <div id="drop-zone">Tournament Players
        
    </div>


    <div id="partialZone">
        @await Component.InvokeAsync("CreatePlayer", new { returnToPlayerPage = false })
    </div>

    <form asp-action="PlayerSetup" method="post" enctype="multipart/form-data">   
        <input type="hidden" asp-for="TournamentId" />

        <div class="form-group">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" name="Name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="form-check">
            <input type="checkbox" asp-for="RandomTeams" checked />
            <label class="form-check-lable" for="RandomTeams">Random Teams</label>
            <input type="checkbox" asp-for="RandomSetup" checked />
            <label class="form-check-lable" for="RandomSetup">Random Setup</label>
            
        </div>

        @foreach (Player player in ViewBag.AllPlayers)
        {
            <div class="form-check">
                @{
                    bool isChecked = Model.Players != null && Model.Players.Any(i => i.PlayerId == player.PlayerId);
                }
                <input type="checkbox" class="form-check-input" id="@player.PlayerId" name="playerIDs" value="@player.PlayerId"
                @(isChecked ? "checked" : "") />
                <label class="form-check-label" for="@player.PlayerId">@player.Name</label>
            </div>
        }
        <button tpye="submit" class="btn btn-primary">Create</button>
    </form>

    <script>
        const pool = document.getElementById('pool');
        const dropZone = document.getElementById('drop-zone');      
   

        function dragStart(event) 
        {
            event.dataTransfer.setData('text', event.squareId);
        }

        function dragEnter(event) 
        {
            event.preventDefault();
            dropZone.style.border = "2px dashed green";
        }

        function dragOver(event) 
        {
            event.preventDefault();
        }

        function dragLeave(event) 
        {
            dropZone.style.border = "1px dashed #ccc";
        }

        function dragDrop(event) 
        {
            event.preventDefault();
            dropZone.style.border = "1px dashed #ccc";
            const draggedElementId = event.dataTransfer.getData('text');
            const draggedElement = document.getElementById(draggedElementId);
            if (draggedElement) {
                dropZone.appendChild(draggedElement);
            }
        }

        dropZone.addEventListener('dragenter', (event) => {
            event.preventDefault();
            dropZone.style.border = "2px dashed green";            
        });

        dropZone.addEventListener('dragover', (event) => {
            event.preventDefault();            
        });

        dropZone.addEventListener('dragleave', (event) => {
            dropZone.style.border = "1px dashed #ccc";  
        });

        dropZone.addEventListener('drop', (event) => {
            event.preventDefault();
            dropZone.style.border = "1px dashed #ccc";
            const draggedElementId = event.dataTransfer.getData('text');
            const draggedElement = document.getElementById(draggedElementId);
            if (draggedElement) {
                dropZone.appendChild(draggedElement);
            }
        });

        // Event listener for the 'x' click
        dropZone.addEventListener('click', (event) => {
            if (event.target.className === 'x') { // Check if the 'x' was clicked
                const square = event.target.parentNode;
                const squareId = square.id;

                console.log(squareId);

                pool.appendChild(square); // Move back to the pool

                const antiForgeryToken = document.querySelector('input[name="__RequestVerificationToken"]').value; // Get the token from the form
                
                $.ajax({ // Use $.ajax for more control
                    type: "POST",
                    url: '@Url.Action("RemovePlayer", "Tournament")',
                    data: { playerId: squareId },
                    headers: {
                        "RequestVerificationToken": antiForgeryToken // Add the token to the headers
                    },
                    success: function (response) {
                        // Handle success (e.g., remove the element from the UI)
                        console.log("Player removed successfully");
                    },
                    error: function (error) {
                        // Handle errors
                        console.error("Error removing player:", error);
                    }
                });
            }
        });


      
    </script>

</body>
</html>